#ifndef DEFINES_H
#define DEFINES_H

#include <cstdint>

#include "raylib.h"

// LIMIT OF 1 BYTE:  uint8_t  = 0 - 255 (INCLUSIVE)
// LIMIT OF 2 BYTES: uint16_t = 0 - 65,535 (INCLUSIVE)
// LIMIT OF 4 BYTES: uint32_t = 0 - 4,294,967,295 (INCLUSIVE)
// LIMIT OF 8 BYTES: uint64_t = 0 - 18,446,744,073,709,551,615 (INCLUSIVE)

// SIMULATION PARAMETERS | MODIFY WITH CARE | Chuu lo, magr pyar sy :)

// WINDOW RELATED
constexpr uint16_t SCREEN_WIDTH = 1660;
constexpr uint16_t SCREEN_HEIGHT = 980;

// PARTICLE RELATED
constexpr uint16_t TOTAL_PARTICLES_COUNT = 20000;     // BE MINDFUL OF THE DATA-TYPE
constexpr uint16_t GENERATE_PARTICLES_PER_SECOND = 1; // FEELS CHAOTIC IF > 4
constexpr uint16_t MAX_PARTICLE_RADIUS = 4;           // BREAKS IF < 3

// GRID RELATED
constexpr uint16_t CELL_SIZE = MAX_PARTICLE_RADIUS * 2;           // PARTICLE WILL ALWAYS BE IN A CELL AT ANY GIVEN TIME
constexpr uint16_t GRID_WIDTH = (SCREEN_WIDTH / CELL_SIZE) + 1;   // GET TOTAL NUMBER OF POSSIBLE HORIZONTAL CELLS
constexpr uint16_t GRID_HEIGHT = (SCREEN_HEIGHT / CELL_SIZE) + 1; // GET TOTAL NUMBER OF POSSIBLE VERTICLE CELLS

// RESISTIVE FORCES
constexpr float GRAVITY = 1000.0f;              // IN VERLET INTEGERATION, HIGHER NUMBER IS OFTEN BETTER
constexpr float FRICTION = 0.99f;               // MOSTLY FOR FLOOR | SMALL, BUT CAN BE USED CONTINUOUSLY
constexpr float DAMPENING = 0.75f;              // MOSTLY FOR WALLS | HIGH,  BUT CAN BE USED SPARSELY
constexpr float COLLISION_REACTION_LOSS = 0.2f; // DON'T ASK ME ABOUT THIS :(

#endif