#ifndef DEFINES_H
#define DEFINES_H

#include <cstdint>

#include "raylib.h"

// A LITTLE NOTE FOR EVERYONE
// LIMIT OF 1 BYTE:  uint8_t  = 0 - 255 (INCLUSIVE)
// LIMIT OF 2 BYTES: uint16_t = 0 - 65,535 (INCLUSIVE)
// LIMIT OF 4 BYTES: uint32_t = 0 - 4,294,967,295 (INCLUSIVE)
// LIMIT OF 8 BYTES: uint64_t = 0 - 18,446,744,073,709,551,615 (INCLUSIVE)

// SIMULATION PARAMETERS | MODIFY WITH CARE | Chhu lo, magar pyar sy :)
// WHAT I MEAN IS, BEFORE CHANGING ANY VALUE, RE-CHECK THE DATA TYPE OF THAT VARIABLE AND ALL OTHER VARIABLES THAT DEPEND ON THAT
// OTHERWISE SIMULATION WILL JUST CRASH, OR BEHAVE ABNORMALLY

// WINDOW RELATED
constexpr uint16_t SCREEN_WIDTH = 1665; // MY SCREEN SIZE, YOU MAY CHANGE IT ACCORDINGLY
constexpr uint16_t SCREEN_HEIGHT = 985;

// PARTICLE RELATED
constexpr uint16_t TOTAL_PARTICLES_COUNT = 19700;     // MAX PARTILCES THAT CAN FIT IN THE WINDOW
constexpr uint16_t GENERATE_PARTICLES_PER_SECOND = 7; // (1 == SINGLE LINE OF STREAM) && (2+ == MULTIPLE JITTERY LINES)
constexpr uint16_t MAX_PARTICLE_RADIUS = 5;           // LOOKS VERY ODD IF >= 10

// GRID RELATED
constexpr uint16_t CELL_SIZE = MAX_PARTICLE_RADIUS << 1;          // PARTICLE WILL ALWAYS BE IN A CELL AT ANY GIVEN TIME
constexpr uint16_t GRID_WIDTH = (SCREEN_WIDTH / CELL_SIZE) + 1;   // GET TOTAL NUMBER OF POSSIBLE HORIZONTAL CELLS
constexpr uint16_t GRID_HEIGHT = (SCREEN_HEIGHT / CELL_SIZE) + 1; // GET TOTAL NUMBER OF POSSIBLE VERTICLE CELLS
constexpr uint32_t TOTAL_CELLS = GRID_WIDTH * GRID_HEIGHT;        // TOTAL NUMBER OF CELLS

// RESISTIVE FORCES
constexpr float GRAVITY = 1000.0f;              // IN VERLET INTEGERATION, HIGHER NUMBER IS OFTEN BETTER
constexpr float FRICTION = 0.99f;               // MOSTLY FOR FLOOR | SMALL, BUT CAN BE USED CONTINUOUSLY
constexpr float DAMPENING = 0.75f;              // MOSTLY FOR WALLS | HIGH,  BUT CAN BE USED SPARSELY
constexpr float COLLISION_REACTION_LOSS = 0.2f; // DON'T ASK ME ABOUT THIS :( THE SIMULATION WAS GOING CRAZY FOR SOME REASON, IT IS JUST TO PREVENT THAT

#endif