#ifndef DEFINES_H
#define DEFINES_H

#include <cstdint>

// A LITTLE NOTE FOR EVERYONE
// LIMIT OF 1 BYTE:  uint8_t  = 0 - 255 (INCLUSIVE)
// LIMIT OF 2 BYTES: uint16_t = 0 - 65,535 (INCLUSIVE)
// LIMIT OF 4 BYTES: uint32_t = 0 - 4,294,967,295 (INCLUSIVE)
// LIMIT OF 8 BYTES: uint64_t = 0 - 18,446,744,073,709,551,615 (INCLUSIVE)

// SIMULATION PARAMETERS | MODIFY WITH CARE | Chhu lo, magar pyar sy :)
// WHAT I MEAN IS, BEFORE CHANGING ANY VALUE, RE-CHECK THE DATA TYPE OF THAT VARIABLE AND ALL OTHER VARIABLES THAT DEPEND ON THAT
// OTHERWISE SIMULATION WILL JUST CRASH, OR BEHAVE ABNORMALLY

// WINDOW RELATED (MY SCREEN SIZE, YOU MAY CHANGE IT ACCORDINGLY)
constexpr uint16_t SCREEN_WIDTH = 1600;
constexpr uint16_t SCREEN_HEIGHT = 990;

// ---------------------------   TIME STEP   ---------------------------

// THE SOLVER RUNS ON A FIXED TIME STEP AND NEVER LOOKS AT THE REAL FRAME TIME.
// FEEDING IT GetFrameTime() IS A DEATH SPIRAL: A SLOW FRAME MEANS A BIGGER STEP,
// A BIGGER STEP MEANS DEEPER OVERLAPS, DEEPER OVERLAPS MEAN MORE SOLVER WORK AND
// AN EVEN SLOWER FRAME. PINNING dt COSTS A LITTLE SLOW-MOTION UNDER HEAVY LOAD
// AND BUYS A SIMULATION THAT CANNOT BLOW ITSELF UP.
constexpr float SIMULATION_FPS = 62.0f;
constexpr float SIMULATION_DT = 1.0f / SIMULATION_FPS;

// SUB-STEPS ARE WHAT KEEP A DEEP PILE FROM ERUPTING.
//
// A PILE HOLDS UP ITS WEIGHT THROUGH THE CONTACT KICK (SEE solveContact), SO THE
// OVERLAP UNDER IT GROWS WITH (PILE DEPTH IN LAYERS / DIAMETER) * SUB_DT^2 DIVIDED
// BY COLLISION_ITERATIONS. ONCE THE MEAN OVERLAP PASSES ABOUT 2.5% THE OPPOSING
// KICKS ON DEEP PARTICLES STOP CANCELLING, SHOCKWAVES RUN THROUGH THE PILE AND THE
// FLOOR THROWS IT INTO THE AIR. A SWEEP COSTS THE SAME EITHER WAY, BUT SUB-STEPS
// SHRINK THE OVERLAP WITH THE SQUARE AND EXTRA PASSES ONLY LINEARLY. HENCE MANY
// SUB-STEPS WITH ONE PASS EACH.
//
// MEASURED POURING 100k, THEN 15 s AT REST, 4 THREADS ON AN M1:
//   6 x 2    ERUPTS FROM 40-50k AND NEVER SETTLES           16.6 ms / FRAME
//   12 x 1   SETTLES AT 60k, ERUPTS AGAIN PAST ~90k          18.0 ms
//   16 x 1   SETTLES AT 100k, 2.6% MEAN OVERLAP, NO MARGIN   19.7 ms
//   18 x 1   SETTLES AT 100k, 2.0% MEAN OVERLAP              23.6 ms
// A DEEPER PILE NEEDS MORE. RADIUS 3 AT 32k ONLY JUST GOT AWAY WITH 6 x 2.
constexpr uint8_t SUB_STEPS = 18;                       // PHYSICS SUB-STEPS PER FRAME
constexpr float SUB_DT = SIMULATION_DT / static_cast<float>(SUB_STEPS);
// SYMMETRIC RELAXATION PASSES PER SUB-STEP, THE BRACE PASS (IF ON) IS EXTRA.
constexpr uint8_t COLLISION_ITERATIONS = 1;

// ---------------------------   PARTICLES   ---------------------------

// MORE PARTICLES OR A SMALLER RADIUS MEANS A DEEPER PILE, WHICH NEEDS MORE SUB_STEPS.
constexpr uint32_t TOTAL_PARTICLES_COUNT = 100000;       // MAX PARTICLES THAT CAN FIT IN THE WINDOW

constexpr float PARTICLE_RADIUS = 2.0f;                     // LOOKS VERY ODD IF >= 10
constexpr float PARTICLE_DIAMETER = PARTICLE_RADIUS * 2.0f; // 6.0f

// ---------------------------   GRID   ---------------------------

constexpr uint16_t CELL_SIZE = static_cast<uint16_t>(PARTICLE_DIAMETER); // PARTICLE WILL ALWAYS BE IN A CELL AT ANY GIVEN TIME
constexpr float INV_CELL_SIZE = 1.0f / static_cast<float>(CELL_SIZE);    // CACHED INVERSE CELL SIZE

constexpr uint16_t GRID_WIDTH = (SCREEN_WIDTH / CELL_SIZE) + 1;       // GET TOTAL NUMBER OF POSSIBLE HORIZONTAL CELLS
constexpr uint16_t GRID_HEIGHT = (SCREEN_HEIGHT / CELL_SIZE) + 1;     // GET TOTAL NUMBER OF POSSIBLE VERTICAL CELLS
constexpr uint32_t TOTAL_CELLS = GRID_WIDTH * GRID_HEIGHT;            // TOTAL NUMBER OF CELLS

// GHOST BOUNDARY (FOR IGNORING BOUNDARY CHECKS IN GRID)
constexpr uint16_t PADDED_GRID_WIDTH = GRID_WIDTH + 2;
constexpr uint16_t PADDED_GRID_HEIGHT = GRID_HEIGHT + 2;
constexpr uint32_t PADDED_TOTAL_CELLS = static_cast<uint32_t>(PADDED_GRID_WIDTH) * static_cast<uint32_t>(PADDED_GRID_HEIGHT);

// THE CELL RANGE TABLE IS INDEXED ONE PAST THE LAST REAL CELL'S BOTTOM-RIGHT
// NEIGHBOUR, PLUS THE +1 BIAS THE COUNTING SORT USES. FOUR SPARE SLOTS COVER IT.
constexpr uint32_t CELL_RANGE_SIZE = PADDED_TOTAL_CELLS + 4;

// ---------------------------   COLLISION   ---------------------------

constexpr float MIN_COLLISION_DIST = PARTICLE_DIAMETER;
constexpr float MIN_COLLISION_DIST_SQ = MIN_COLLISION_DIST * MIN_COLLISION_DIST;

// ---------------------------   RESISTIVE FORCES & PHYSICS   ---------------------------

constexpr float GRAVITY = 1000.0f;               // GRAVITATIONAL ACCELERATION (PIXELS PER SECOND SQUARED)

// ---------------------------   MATERIAL CHARACTER   ---------------------------

// WHAT SEPARATES DRY SAND FROM THE LOOSE, SPRINGY, HALF-LIQUID MATERIAL THIS
// SIMULATION POURS IS SHEAR STRENGTH: WHETHER A HEAP CAN HOLD A SLOPE. FRICTIONLESS
// DISCS CANNOT. IF THIS PILE EVER STANDS UP LIKE A DUNE, SOMETHING IN HERE IS
// SMUGGLING FRICTION IN THROUGH THE BACK DOOR.

// HOW MUCH OF A MEASURED OVERLAP THE POSITIONAL PASS REMOVES PER ITERATION.
// 1.0 IS FULL PROJECTION, WHICH IS WHAT THE ORIGINAL VERLET SOLVER DID.
constexpr float POSITION_CORRECTION = 1.0f;

// PENETRATION THIS SHALLOW IS LEFT ALONE. A SLOP BAND STOPS A RESTING PILE FROM
// TWITCHING, BUT IT ALSO LETS NEIGHBOURS SIT LOCKED INSIDE EACH OTHER, WHICH READS
// AS GRAIN INTERLOCK. ZERO MEANS EVERY OVERLAP IS ALWAYS PUSHED OUT.
constexpr float PENETRATION_SLOP = 0.0f;

// THE SEPARATION SPRING. THIS IS THE ORIGINAL VERLET SOLVER'S CONTACT RESPONSE:
// THE POSITION FIX IS FED BACK INTO VELOCITY, LESS WHATEVER THIS THROWS AWAY.
//
// IT IS WHAT MAKES CONTACTS POP, HEAPS SLUMP AND THE STREAM SPLASH, AND IT IS ALSO
// THE ONLY THING THAT ACTIVELY DRIVES A COMPACTED PILE BACK APART. REPLACING IT
// WITH A TEXTBOOK RESTITUTION IMPULSE, WHICH CANNOT PUSH HARDER THAN THE PAIR
// ARRIVED, LOOKS CORRECT AND IS NOT: A DEEP PILE THEN SINKS INTO ITSELF AND SITS
// THERE AT 32% MEAN INTERPENETRATION FOREVER.
//
// 0.0 = THE FULL SHOVE BECOMES SPEED.
// 0.2 = THE ORIGINAL VALUE.
// 1.0 = NO VELOCITY CHANGE AT ALL, PURE POSITION PROJECTION.
constexpr float COLLISION_REACTION_LOSS = 0.20f;

// THE SEPARATION IS MEASURED IN PIXELS BUT APPLIED TO A VELOCITY, SO IT HAS TO BE
// DIVIDED BY THE SUB-STEP. THE OLD SOLVER GOT THIS FOR FREE BECAUSE IT KEPT
// VELOCITY AS (pos - oldPos) AND A POSITION EDIT WAS A VELOCITY EDIT.
constexpr float CONTACT_KICK = (1.0f - COLLISION_REACTION_LOSS) / SUB_DT;

// AN OPTIONAL CEILING ON THAT SPRING. OFF (0.0) AND COMPILED OUT BY DEFAULT.
//
// THE SPRING IS PROPORTIONAL TO OVERLAP AND CANNOT TELL AN IMPACT FROM A PILE
// RESTING ON ITS OWN WEIGHT, SO CAPPING IT LOOKS LIKE THE CURE FOR THE EXPLOSION
// OFF THE FLOOR. IT IS NOT. THE CURE IS THE SUB-STEP SIZE, SEE SUB_STEPS.
//
// CAPPING THE SPRING BARELY WORKS. MEASURED AT 60k WITH 6 SUB-STEPS x 2 PASSES,
// FRACTION OF PARTICLES STILL BEING THROWN UPWARD AFTER 25 SECONDS AT REST:
//   OFF 19.0%   CAP 800 40.1%   CAP 400 17.5%   CAP 200 13.1%   CAP 100 24.4%
// TIGHTENING IT BACKFIRES: BELOW ABOUT 400 THE CAP STARVES THE SPRING OF THE
// SEPARATION POWER THE PILE NEEDS, THE PILE COMPACTS INSTEAD, AND MORE CONTACTS
// THEN SIT PINNED AT THE CAP FIRING CONTINUOUSLY. THE BEST SETTING COSTS 14%
// PERFORMANCE TO MOVE 19.0% TO 17.5%, WHICH IS NOT A TRADE WORTH MAKING, SO IT IS
// OFF. 400 IS THE VALUE TO TRY FIRST IF YOU WANT TO EXPERIMENT.
constexpr float MAX_CONTACT_KICK = 0.0f;

// THE BRACE PASS. PINS THE LOWER PARTICLE'S VERTICAL SHARE OF A CONTACT SO THE
// FLOOR'S SUPPORT CLIMBS A COLUMN IN ONE SWEEP INSTEAD OF BEING HALVED AT EVERY
// LAYER. SYMMETRIC RELAXATION ALONE REACHES THE TOP OF A SEVENTY-LAYER PILE AT
// 2^-70, WHICH IS WHY THE SPRING ABOVE HAS TO DO THAT JOB INSTEAD.
//
// LEFT OFF ON PURPOSE. PINNING MEANS THE UPPER PARTICLE ABSORBS THE WHOLE
// CORRECTION, SO EVERY CONTACT NUDGES THE PAIR'S CENTRE OF MASS UPWARD. A STATIC
// PILE CANCELS THAT AGAINST GRAVITY; A POURING ONE DOES NOT, AND THE MATERIAL
// INFLATES, FREEZES INTO ARCHES AND CLIMBS THE WALLS. IT COSTS AN EXTRA CONTACT
// PASS TO DO IT, TOO. MEASURED: 10.5% MEAN OVERLAP WHILE POURING AT HALF STRENGTH,
// 36% AT FULL, AGAINST 3.9% WITH IT OFF.
constexpr float VERTICAL_BRACE = 0.0f;

// INTER-PARTICLE TANGENTIAL SHEAR. THIS IS WHAT GIVES A HEAP AN ANGLE OF REPOSE.
// ZERO LETS PARTICLES SLIDE FREELY OVER ONE ANOTHER, WHICH IS THE FLUID HINT.
constexpr float PARTICLE_FRICTION = 0.0f;

// COMPILE-TIME HELPERS FOR RESCALING A PER-SUB-STEP RATE. x^n, AND THE x FOR WHICH
// x^n == a (NEWTON'S METHOD, a NEAR 1).
constexpr double constexprPow(const double x, uint32_t n)
{
    double r = 1.0;
    while (n--)
    {
        r *= x;
    }
    return r;
}

constexpr double constexprRoot(const double a, const uint32_t n)
{
    double x = 1.0;
    for (int i = 0; i < 16; i++)
    {
        x -= (constexprPow(x, n) - a) / (static_cast<double>(n) * constexprPow(x, n - 1u));
    }
    return x;
}

// TANGENTIAL VELOCITY RETAINED ON A WALL HIT. A PARTICLE LYING ON THE FLOOR IS HIT
// EVERY SUB-STEP, SO THIS IS REALLY A DRAG RATE, AND 0.99 WAS TUNED AT 6 SUB-STEPS.
// SPREADING THAT SAME DRAG OVER SUB_STEPS KEEPS THE FLOOR EXACTLY AS SLIPPERY PER
// SECOND WHATEVER THE SUB-STEP COUNT IS.
constexpr float WALL_FRICTION_AT_6_SUB_STEPS = 0.99f;
constexpr float WALL_FRICTION = static_cast<float>(
    constexprRoot(constexprPow(WALL_FRICTION_AT_6_SUB_STEPS, 6u), SUB_STEPS));

constexpr float WALL_RESTITUTION = 0.75f;        // NORMAL VELOCITY RETAINED ON A HARD WALL HIT
constexpr float WALL_RESTING_SPEED = 0.0f;       // NORMAL SPEED (PX/S) BELOW WHICH A WALL HIT STOPS
                                                 // BOUNCING. 0 KEEPS THE FLOOR LIVE, THE WAY IT WAS.

// A PARTICLE MUST NEVER TRAVEL FURTHER THAN ONE CELL IN A SINGLE SUB-STEP OR IT
// CAN PASS CLEAN THROUGH A NEIGHBOUR BEFORE THE GRID EVER SEES THE CONTACT.
// THIS IS A SAFETY VALVE, NOT A DRAG TERM: NORMAL PLAY NEVER REACHES IT.
constexpr float MAX_SPEED = PARTICLE_DIAMETER * static_cast<float>(SUB_STEPS) * SIMULATION_FPS * 0.7f;
constexpr float MAX_SPEED_SQ = MAX_SPEED * MAX_SPEED;

// ---------------------------   MOUSE INTERACTION   ---------------------------

constexpr float MOUSE_FORCE = 45000.0f;          // ACCELERATION AT THE CURSOR CENTRE (PX/S^2)
constexpr float MOUSE_PULL_DAMPING = 0.85f;      // VELOCITY RETAINED PER FRAME INSIDE A PULL,
                                                 // OTHERWISE PARTICLES SLINGSHOT THROUGH THE CENTRE

// ---------------------------   EMITTER   ---------------------------

// THE EMITTER IS A NOZZLE, NOT A POINT. A POINT SOURCE CANNOT PHYSICALLY PASS
// MORE THAN (SPEED / DIAMETER) PARTICLES PER SECOND WITHOUT STACKING THEM INSIDE
// EACH OTHER, AND A STACK OF CO-LOCATED PARTICLES IS A GRENADE: THE SOLVER SEES A
// HUGE OVERLAP AND CONVERTS IT STRAIGHT INTO SPEED. SO WE LAY NEW PARTICLES OUT
// ON A LATTICE ACROSS A NOZZLE OF REAL WIDTH, SPACED SO THEY NEVER TOUCH AT BIRTH.
// AIM MATTERS MORE THAN IT LOOKS. A JET THAT DROPS ITS MATERIAL NEAR ITS OWN
// MOUTH BUILDS A HEAP THAT CLIMBS BACK UP AND SWALLOWS THE NOZZLE, AND SINCE THE
// NOZZLE REFUSES TO FIRE INTO OCCUPIED SPACE THE SIMULATION THEN STALLS AT HALF
// CAPACITY. THROWING THE STREAM AT THE OPPOSITE WALL FILLS THE BOX FROM THE FAR
// SIDE INSTEAD, THE WAY YOU WOULD ACTUALLY POUR ONE, AND THE MOUTH IS THE LAST
// THING TO GET BURIED.
constexpr float EMITTER_POS_X = SCREEN_WIDTH - 60.0f;
constexpr float EMITTER_POS_Y = 70.0f;

constexpr float EMITTER_SPEED = 1050.0f;         // MUZZLE SPEED IN PIXELS PER SECOND
constexpr float EMITTER_DIR_X = -0.997f;         // MUST BE UNIT LENGTH
constexpr float EMITTER_DIR_Y = 0.077f;

constexpr float EMITTER_NOZZLE_WIDTH = 80.0f;    // NOZZLE EXTENT PERPENDICULAR TO THE FLOW

// ORGANIC VARIATION. KEPT ON THE VELOCITY, NOT THE POSITION: POSITION JITTER
// LARGE ENOUGH TO SEE WOULD PUT PARTICLES BACK INSIDE EACH OTHER.
constexpr float EMITTER_SPEED_JITTER = 0.04f;    // +/- FRACTION OF MUZZLE SPEED
constexpr float EMITTER_SPREAD = 14.0f;          // +/- PERPENDICULAR VELOCITY IN PIXELS PER SECOND

// LATTICE GEOMETRY, ALL DERIVED. LANES RUN ACROSS THE NOZZLE, RINGS RUN ALONG THE
// FLOW INSIDE THE DISTANCE THE STREAM COVERS IN ONE FRAME.
constexpr float SPAWN_SPACING = PARTICLE_DIAMETER * 1.06f;
constexpr float EMITTER_STEP = EMITTER_SPEED * SIMULATION_DT;

constexpr uint32_t EMITTER_LANES =
    (static_cast<uint32_t>(EMITTER_NOZZLE_WIDTH / SPAWN_SPACING) > 1u)
        ? static_cast<uint32_t>(EMITTER_NOZZLE_WIDTH / SPAWN_SPACING)
        : 1u;

constexpr uint32_t EMITTER_RINGS =
    (static_cast<uint32_t>(EMITTER_STEP / SPAWN_SPACING) > 1u)
        ? static_cast<uint32_t>(EMITTER_STEP / SPAWN_SPACING)
        : 1u;

// THE MOST THE NOZZLE CAN PASS PER FRAME WITHOUT OVERLAPPING ITS OWN OUTPUT.
// ASKING generateParticles() FOR MORE THAN THIS SIMPLY CHOKES, THE WAY A REAL
// NOZZLE WOULD, INSTEAD OF SPAWNING A BOMB.
constexpr uint32_t EMITTER_CAPACITY = EMITTER_LANES * EMITTER_RINGS;
constexpr uint32_t SPAWN_PER_FRAME = EMITTER_CAPACITY;

static_assert(TOTAL_PARTICLES_COUNT > 0, "Need at least one particle");
static_assert(CELL_SIZE >= static_cast<uint16_t>(PARTICLE_DIAMETER),
              "Cell must be at least a particle diameter or the 3x3 search misses contacts");

#endif
