#ifndef DEFINES_H
#define DEFINES_H

#include <cstdint>

// A LITTLE NOTE FOR EVERYONE
// LIMIT OF 1 BYTE:  uint8_t  = 0 - 255 (INCLUSIVE)
// LIMIT OF 2 BYTES: uint16_t = 0 - 65,535 (INCLUSIVE)
// LIMIT OF 4 BYTES: uint32_t = 0 - 4,294,967,295 (INCLUSIVE)
// LIMIT OF 8 BYTES: uint64_t = 0 - 18,446,744,073,709,551,615 (INCLUSIVE)

// SIMULATION PARAMETERS | MODIFY WITH CARE | Chhu lo, magar pyar sy :)
// WHAT I MEAN IS, BEFORE CHANGING ANY VALUE, RE-CHECK THE DATA TYPE OF THAT VARIABLE AND ALL OTHER VARIABLES THAT DEPEND ON THAT
// OTHERWISE SIMULATION WILL JUST CRASH, OR BEHAVE ABNORMALLY

// WINDOW RELATED (MY SCREEN SIZE, YOU MAY CHANGE IT ACCORDINGLY)
constexpr uint16_t SCREEN_WIDTH = 1500;
constexpr uint16_t SCREEN_HEIGHT = 990;

// ---------------------------   TIME STEP   ---------------------------

// THE SOLVER RUNS ON A FIXED TIME STEP AND NEVER LOOKS AT THE REAL FRAME TIME.
// FEEDING IT GetFrameTime() IS A DEATH SPIRAL: A SLOW FRAME MEANS A BIGGER STEP,
// A BIGGER STEP MEANS DEEPER OVERLAPS, DEEPER OVERLAPS MEAN MORE SOLVER WORK AND
// AN EVEN SLOWER FRAME. PINNING dt COSTS A LITTLE SLOW-MOTION UNDER HEAVY LOAD
// AND BUYS A SIMULATION THAT CANNOT BLOW ITSELF UP.
constexpr float SIMULATION_FPS = 60.0f;
constexpr float SIMULATION_DT = 1.0f / SIMULATION_FPS;

constexpr uint8_t SUB_STEPS = 6;                        // PHYSICS SUB-STEPS PER FRAME
constexpr float SUB_DT = SIMULATION_DT / static_cast<float>(SUB_STEPS);
// SYMMETRIC RELAXATION PASSES PER SUB-STEP, THE SHOCK PASS (IF ON) IS EXTRA.
// TWO, NOT ONE. WITHOUT THE SHOCK PASS THE ONLY THING HOLDING A DEEP PILE APART IS
// GEOMETRY, AND ONE GAUSS-SEIDEL SWEEP CANNOT SUPPORT A HUNDRED STACKED LAYERS: THE
// BOTTOM OVERLAPS KEEP GROWING, THE SEPARATION KICK GROWS WITH THEM, AND THE WHOLE
// BOX ENDS UP BOILING. THE SECOND PASS COSTS EXACTLY WHAT THE SHOCK PASS USED TO.
constexpr uint8_t COLLISION_ITERATIONS = 2;

// ---------------------------   PARTICLES   ---------------------------

constexpr uint32_t TOTAL_PARTICLES_COUNT = 32000;       // MAX PARTICLES THAT CAN FIT IN THE WINDOW

constexpr float PARTICLE_RADIUS = 3.0f;                     // LOOKS VERY ODD IF >= 10
constexpr float PARTICLE_DIAMETER = PARTICLE_RADIUS * 2.0f; // 6.0f

// ---------------------------   GRID   ---------------------------

constexpr uint16_t CELL_SIZE = static_cast<uint16_t>(PARTICLE_DIAMETER); // PARTICLE WILL ALWAYS BE IN A CELL AT ANY GIVEN TIME
constexpr float INV_CELL_SIZE = 1.0f / static_cast<float>(CELL_SIZE);    // CACHED INVERSE CELL SIZE

constexpr uint16_t GRID_WIDTH = (SCREEN_WIDTH / CELL_SIZE) + 1;       // GET TOTAL NUMBER OF POSSIBLE HORIZONTAL CELLS
constexpr uint16_t GRID_HEIGHT = (SCREEN_HEIGHT / CELL_SIZE) + 1;     // GET TOTAL NUMBER OF POSSIBLE VERTICAL CELLS
constexpr uint32_t TOTAL_CELLS = GRID_WIDTH * GRID_HEIGHT;            // TOTAL NUMBER OF CELLS

// GHOST BOUNDARY (FOR IGNORING BOUNDARY CHECKS IN GRID)
constexpr uint16_t PADDED_GRID_WIDTH = GRID_WIDTH + 2;
constexpr uint16_t PADDED_GRID_HEIGHT = GRID_HEIGHT + 2;
constexpr uint32_t PADDED_TOTAL_CELLS = static_cast<uint32_t>(PADDED_GRID_WIDTH) * static_cast<uint32_t>(PADDED_GRID_HEIGHT);

// THE CELL RANGE TABLE IS INDEXED ONE PAST THE LAST REAL CELL'S BOTTOM-RIGHT
// NEIGHBOUR, PLUS THE +1 BIAS THE COUNTING SORT USES. FOUR SPARE SLOTS COVER IT.
constexpr uint32_t CELL_RANGE_SIZE = PADDED_TOTAL_CELLS + 4;

// ---------------------------   COLLISION   ---------------------------

constexpr float MIN_COLLISION_DIST = PARTICLE_DIAMETER;
constexpr float MIN_COLLISION_DIST_SQ = MIN_COLLISION_DIST * MIN_COLLISION_DIST;

// ---------------------------   RESISTIVE FORCES & PHYSICS   ---------------------------

constexpr float GRAVITY = 1000.0f;               // GRAVITATIONAL ACCELERATION (PIXELS PER SECOND SQUARED)

// ---------------------------   MATERIAL CHARACTER   ---------------------------

// THE FOUR KNOBS BELOW DECIDE WHETHER THE HEAP BEHAVES LIKE DRY SAND OR LIKE THE
// LOOSE, SPRINGY, HALF-LIQUID MATERIAL THIS SIMULATION IS SUPPOSED TO POUR.
//
// SAND WANTS: SHOCK_PROPAGATION ON, PARTICLE_FRICTION AROUND 0.3, A SLOP BAND, AND
// A CONTACT THAT CANCELS THE APPROACH SPEED. EVERY CONTACT GOES DEAD, PILES HOLD A
// STEEP FACE AND NOTHING EVER SPLASHES.
//
// THE ORIGINAL LOOK WANTS THE OPPOSITE OF ALL FOUR, WHICH IS WHAT IS SET HERE.

// PINS THE LOWER PARTICLE OF EVERY CONTACT SO THE FLOOR'S SUPPORT REACHES THE TOP
// OF A COLUMN IN ONE SWEEP. IT IS THE SINGLE BIGGEST REASON A PILE STANDS UP LIKE
// A SAND DUNE INSTEAD OF SLUMPING, SO IT IS OFF.
constexpr bool SHOCK_PROPAGATION = false;

// HOW MUCH OF A MEASURED OVERLAP THE POSITIONAL PASS REMOVES PER ITERATION.
// 1.0 IS FULL PROJECTION, WHICH IS WHAT THE ORIGINAL VERLET SOLVER DID.
constexpr float POSITION_CORRECTION = 1.0f;

// PENETRATION THIS SHALLOW IS LEFT ALONE. A SLOP BAND STOPS A RESTING PILE FROM
// TWITCHING, BUT IT ALSO LETS NEIGHBOURS SIT LOCKED INSIDE EACH OTHER, WHICH READS
// AS GRAIN INTERLOCK. ZERO MEANS EVERY OVERLAP IS ALWAYS PUSHED OUT.
constexpr float PENETRATION_SLOP = 0.0f;

// FRACTION OF THE SEPARATION KICK THAT IS THROWN AWAY AT EACH CONTACT.
// 0.0 = THE FULL SHOVE BECOMES SPEED AND THE HEAP BOILS.
// 0.2 = THE ORIGINAL VALUE. CONTACTS POP, HEAPS SLUMP AND SPREAD, THE STREAM
//       SPLASHES WHERE IT LANDS.
// 1.0 = NO VELOCITY CHANGE AT ALL, PURE POSITION PROJECTION. CALM AND STILL.
constexpr float COLLISION_REACTION_LOSS = 0.20f;

// THE SEPARATION IS MEASURED IN PIXELS BUT APPLIED TO A VELOCITY, SO IT HAS TO BE
// DIVIDED BY THE SUB-STEP. THE OLD SOLVER GOT THIS FOR FREE BECAUSE IT KEPT
// VELOCITY AS (pos - oldPos) AND A POSITION EDIT WAS A VELOCITY EDIT.
constexpr float CONTACT_KICK = (1.0f - COLLISION_REACTION_LOSS) / SUB_DT;

// INTER-PARTICLE TANGENTIAL SHEAR. THIS IS WHAT GIVES A HEAP AN ANGLE OF REPOSE.
// ZERO LETS PARTICLES SLIDE FREELY OVER ONE ANOTHER, WHICH IS THE FLUID HINT.
constexpr float PARTICLE_FRICTION = 0.0f;

constexpr float WALL_FRICTION = 0.99f;           // TANGENTIAL VELOCITY RETAINED ON A WALL HIT
constexpr float WALL_RESTITUTION = 0.75f;        // NORMAL VELOCITY RETAINED ON A HARD WALL HIT
constexpr float WALL_RESTING_SPEED = 0.0f;       // NORMAL SPEED (PX/S) BELOW WHICH A WALL HIT STOPS
                                                 // BOUNCING. 0 KEEPS THE FLOOR LIVE, THE WAY IT WAS.

// A PARTICLE MUST NEVER TRAVEL FURTHER THAN ONE CELL IN A SINGLE SUB-STEP OR IT
// CAN PASS CLEAN THROUGH A NEIGHBOUR BEFORE THE GRID EVER SEES THE CONTACT.
// THIS IS A SAFETY VALVE, NOT A DRAG TERM: NORMAL PLAY NEVER REACHES IT.
constexpr float MAX_SPEED = PARTICLE_DIAMETER * static_cast<float>(SUB_STEPS) * SIMULATION_FPS * 0.7f;
constexpr float MAX_SPEED_SQ = MAX_SPEED * MAX_SPEED;

// ---------------------------   MOUSE INTERACTION   ---------------------------

constexpr float MOUSE_FORCE = 45000.0f;          // ACCELERATION AT THE CURSOR CENTRE (PX/S^2)
constexpr float MOUSE_PULL_DAMPING = 0.85f;      // VELOCITY RETAINED PER FRAME INSIDE A PULL,
                                                 // OTHERWISE PARTICLES SLINGSHOT THROUGH THE CENTRE

// ---------------------------   EMITTER   ---------------------------

// THE EMITTER IS A NOZZLE, NOT A POINT. A POINT SOURCE CANNOT PHYSICALLY PASS
// MORE THAN (SPEED / DIAMETER) PARTICLES PER SECOND WITHOUT STACKING THEM INSIDE
// EACH OTHER, AND A STACK OF CO-LOCATED PARTICLES IS A GRENADE: THE SOLVER SEES A
// HUGE OVERLAP AND CONVERTS IT STRAIGHT INTO SPEED. SO WE LAY NEW PARTICLES OUT
// ON A LATTICE ACROSS A NOZZLE OF REAL WIDTH, SPACED SO THEY NEVER TOUCH AT BIRTH.
// AIM MATTERS MORE THAN IT LOOKS. A JET THAT DROPS ITS MATERIAL NEAR ITS OWN
// MOUTH BUILDS A HEAP THAT CLIMBS BACK UP AND SWALLOWS THE NOZZLE, AND SINCE THE
// NOZZLE REFUSES TO FIRE INTO OCCUPIED SPACE THE SIMULATION THEN STALLS AT HALF
// CAPACITY. THROWING THE STREAM AT THE OPPOSITE WALL FILLS THE BOX FROM THE FAR
// SIDE INSTEAD, THE WAY YOU WOULD ACTUALLY POUR ONE, AND THE MOUTH IS THE LAST
// THING TO GET BURIED.
constexpr float EMITTER_POS_X = SCREEN_WIDTH - 60.0f;
constexpr float EMITTER_POS_Y = 70.0f;

constexpr float EMITTER_SPEED = 1050.0f;         // MUZZLE SPEED IN PIXELS PER SECOND
constexpr float EMITTER_DIR_X = -0.997f;         // MUST BE UNIT LENGTH
constexpr float EMITTER_DIR_Y = 0.077f;

constexpr float EMITTER_NOZZLE_WIDTH = 80.0f;    // NOZZLE EXTENT PERPENDICULAR TO THE FLOW

// ORGANIC VARIATION. KEPT ON THE VELOCITY, NOT THE POSITION: POSITION JITTER
// LARGE ENOUGH TO SEE WOULD PUT PARTICLES BACK INSIDE EACH OTHER.
constexpr float EMITTER_SPEED_JITTER = 0.04f;    // +/- FRACTION OF MUZZLE SPEED
constexpr float EMITTER_SPREAD = 14.0f;          // +/- PERPENDICULAR VELOCITY IN PIXELS PER SECOND

// LATTICE GEOMETRY, ALL DERIVED. LANES RUN ACROSS THE NOZZLE, RINGS RUN ALONG THE
// FLOW INSIDE THE DISTANCE THE STREAM COVERS IN ONE FRAME.
constexpr float SPAWN_SPACING = PARTICLE_DIAMETER * 1.06f;
constexpr float EMITTER_STEP = EMITTER_SPEED * SIMULATION_DT;

constexpr uint32_t EMITTER_LANES =
    (static_cast<uint32_t>(EMITTER_NOZZLE_WIDTH / SPAWN_SPACING) > 1u)
        ? static_cast<uint32_t>(EMITTER_NOZZLE_WIDTH / SPAWN_SPACING)
        : 1u;

constexpr uint32_t EMITTER_RINGS =
    (static_cast<uint32_t>(EMITTER_STEP / SPAWN_SPACING) > 1u)
        ? static_cast<uint32_t>(EMITTER_STEP / SPAWN_SPACING)
        : 1u;

// THE MOST THE NOZZLE CAN PASS PER FRAME WITHOUT OVERLAPPING ITS OWN OUTPUT.
// ASKING generateParticles() FOR MORE THAN THIS SIMPLY CHOKES, THE WAY A REAL
// NOZZLE WOULD, INSTEAD OF SPAWNING A BOMB.
constexpr uint32_t EMITTER_CAPACITY = EMITTER_LANES * EMITTER_RINGS;
constexpr uint32_t SPAWN_PER_FRAME = EMITTER_CAPACITY;

static_assert(TOTAL_PARTICLES_COUNT > 0, "Need at least one particle");
static_assert(CELL_SIZE >= static_cast<uint16_t>(PARTICLE_DIAMETER),
              "Cell must be at least a particle diameter or the 3x3 search misses contacts");

#endif
