#ifndef PARTICLES_H
#define PARTICLES_H

#include <raylib.h>

#include "defines.hpp"

// STRUCTURE OF ARRAYS. EVERY PHYSICS PASS WALKS ONE FIELD AT A TIME, SO KEEPING
// THE FIELDS IN SEPARATE STREAMS MEANS EVERY CACHE LINE LOADED IS A CACHE LINE
// FULLY USED, AND THE COMPILER CAN AUTO-VECTORISE THE INTEGRATOR.
//
// THESE ARE POINTERS, NOT ARRAYS. THE SOLVER REORDERS PARTICLES INTO SPATIAL
// ORDER EVERY SUB-STEP AND DOES IT BY WRITING INTO A SECOND SET OF BUFFERS AND
// FLIPPING THESE POINTERS, WHICH IS HALF THE MEMORY TRAFFIC OF SHUFFLING INTO A
// SCRATCH BUFFER AND THEN COPYING BACK.
//
// VELOCITY IS STORED EXPLICITLY RATHER THAN IMPLIED BY A PREVIOUS POSITION.
// WITH VERLET'S IMPLICIT VELOCITY, ANY POSITION FIX-UP SILENTLY DOUBLES AS A
// VELOCITY CHANGE. STORING IT HERE MAKES THAT COUPLING A CHOICE INSTEAD OF AN
// ACCIDENT: THE CONTACT SOLVER STILL FEEDS THE POSITION FIX BACK INTO VELOCITY,
// BECAUSE THAT SPRING IS THE LOOK OF THIS SIMULATION, BUT IT DOES IT THROUGH ONE
// NAMED CONSTANT (COLLISION_REACTION_LOSS) THAT CAN BE DIALLED OR TURNED OFF.
struct Particle
{
    static float *posX;
    static float *posY;

    static float *velX; // PIXELS PER SECOND
    static float *velY;

    static Color *color;

    static constexpr float radius = PARTICLE_RADIUS;
};

#endif
